### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by dr013** [lestrrat/go-libxml2#42]
Hi!
Please, add handler for this exception:
```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f18bcdfb049 pc=0xa6c9d0]

runtime stack:
runtime.throw(0xbdce18, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 236 [syscall, locked to thread]:
runtime.cgocall(0xa6bc50, 0xc4207bc578, 0xc400a6c880)
        /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc4207bc548 sp=0xc4207bc508 pc=0x40ee34
github.com/lestrrat/go-libxml2/clib._Cfunc_xmlSchemaValidateDoc(0x7f18801a2510, 0x7f188c52fae0, 0x0)
        github.com/lestrrat/go-libxml2/clib/_obj/_cgo_gotypes.go:1458 +0x4d fp=0xc4207bc578 sp=0xc4207bc548 pc=0x8c12a
d
github.com/lestrrat/go-libxml2/clib.XMLSchemaValidateDocument.func5(0x7f18801a2510, 0x7f188c52fae0, 0x7f1880190d70)
        /srv/rrload/src/github.com/lestrrat/go-libxml2/clib/clib.go:2122 +0xa3 fp=0xc4207bc5b0 sp=0xc4207bc578 pc=0x8c
dab3
github.com/lestrrat/go-libxml2/clib.XMLSchemaValidateDocument(0x114f6a0, 0xc4207efaf0, 0x114f460, 0xc420674010, 0x0, 0
x0, 0x0)
        /srv/rrload/src/github.com/lestrrat/go-libxml2/clib/clib.go:2122 +0x2a8 fp=0xc4207bc668 sp=0xc4207bc5b0 pc=0x8
c9d48
github.com/lestrrat/go-libxml2/xsd.(*Schema).Validate(0xc4207efaf0, 0x115f480, 0xc420674010, 0xc4207efaf0, 0x0)
        /srv/rrload/src/github.com/lestrrat/go-libxml2/xsd/xsd.go:54 +0x73 fp=0xc4207bc6c8 sp=0xc4207bc668 pc=0x979503
gitlab.*****.ru/EKryukov/registry-fileserver/app/jobs.validateXSD(0xbbd458, 0x3, 0x115f480, 0xc420674010, 0xc42062
e870, 0x4e, 0x1, 0x0, 0x0, 0x0, ...)```

**Comment by lestrrat** [comment]
@dr013 sorry for not replying. Can you please make provide a minimal test case that reproduces this?

**Comment by dr013** [comment]
Old version libxml2 issue, fixed after update.
